// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {lunii} from '../models';
import {uuid} from '../models';

export function ListPacks():Promise<Array<lunii.Metadata>>;

export function RemovePack(arg1:uuid.UUID):Promise<boolean|Error>;

export function ChangePackOrder(arg1:uuid.UUID,arg2:number):Promise<string|Error>;

export function CreatePack():Promise<string|Error>;

export function GetDeviceInfos():Promise<lunii.Device>;

export function InstallPack():Promise<string|Error>;
