// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RemovePack(arg1) {
  return window['go']['main']['App']['RemovePack'](arg1);
}

export function SyncStudioMetadata(arg1, arg2) {
  return window['go']['main']['App']['SyncStudioMetadata'](arg1, arg2);
}

export function ChangePackOrder(arg1, arg2) {
  return window['go']['main']['App']['ChangePackOrder'](arg1, arg2);
}

export function CreatePack(arg1, arg2) {
  return window['go']['main']['App']['CreatePack'](arg1, arg2);
}

export function ListPacks() {
  return window['go']['main']['App']['ListPacks']();
}

export function OpenDirectory(arg1) {
  return window['go']['main']['App']['OpenDirectory'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function GetDeviceInfos() {
  return window['go']['main']['App']['GetDeviceInfos']();
}

export function InstallPack() {
  return window['go']['main']['App']['InstallPack']();
}

export function SaveFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2, arg3);
}

export function SyncLuniiStoreMetadata(arg1) {
  return window['go']['main']['App']['SyncLuniiStoreMetadata'](arg1);
}
