// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListPacks() {
  return window['go']['main']['App']['ListPacks']();
}

export function RemovePack(arg1) {
  return window['go']['main']['App']['RemovePack'](arg1);
}

export function ChangePackOrder(arg1, arg2) {
  return window['go']['main']['App']['ChangePackOrder'](arg1, arg2);
}

export function CreatePack() {
  return window['go']['main']['App']['CreatePack']();
}

export function GetDeviceInfos() {
  return window['go']['main']['App']['GetDeviceInfos']();
}

export function InstallPack() {
  return window['go']['main']['App']['InstallPack']();
}
