// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {lunii} from '../models';

export function GetDeviceInfos():Promise<lunii.Device>;

export function InstallPack():Promise<string|Error>;

export function ListPacks():Promise<Array<lunii.Metadata>>;

export function RemovePack(arg1:string):Promise<boolean|Error>;

export function CreatePack():Promise<string|Error>;
