name: Build next

on:
  push:
    branches:
      - main

env:
  NR_LICENCE: ${{ secrets.NR_LICENCE }}

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: Get-Location
      - run: ls D:/a/lunii-admin/lunii-admin/bindings/windows/lib

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.18.0"
          cache: true

      - name: Set up Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@master

      - name: Build
        working-directory: ./cmd/app
        env:
          CGO_LDFLAGS: "-LD:/a/lunii-admin/lunii-admin/bindings/windows/lib"
          CGO_CFLAGS: "-ID:/a/lunii-admin/lunii-admin/bindings/windows/include"
        run: |
          go generate && wails build -debug  -skipbindings -o lunii-admin_windows_amd64.exe -ldflags "-v '-extldflags=-static -lm' -X main.NR_LICENCE=$NR_LICENCE -X main.version=$(git describe --tags --abbrev=0)"

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          replacesArtifacts: true
          artifacts: "build/bin/lunii-admin_windows_amd64.exe"
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          tag: next

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Linux Wails deps
        run: sudo apt-get update && sudo apt-get install libgtk-3-0 libwebkit2gtk-4.0-dev gcc-aarch64-linux-gnu

      - run: sudo apt install libmp3lame-dev

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.18.0"
          cache: true

      - name: Set up Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@master

      - name: Build
        working-directory: ./cmd/app
        run: wails build -ldflags "-X main.NR_LICENCE=$NR_LICENCE -X main.version=$(git describe --tags --abbrev=0)" -debug  -skipbindings -o lunii-admin_linux_amd64

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          replacesArtifacts: true
          artifacts: "build/bin/lunii-admin_linux_amd64"
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          tag: next

  build-macos-amd:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # LAme is installed, but we want to remove the dynamic lib
      - name: Delete dynamic version of Lame
        run: rm /usr/local/opt/lame/lib/libmp3lame.0.dylib

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.18.0"
          cache: true

      - name: Set up Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@master

      - name: Build
        working-directory: ./cmd/app
        run: wails build -ldflags "-X main.NR_LICENCE=$NR_LICENCE -X main.version=$(git describe --tags --abbrev=0)" -debug -skipbindings

      - name: Create Zip
        run: ditto -c -k --sequesterRsrc --keepParent build/bin/lunii-admin.app lunii-admin_darwin_amd64.zip

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          replacesArtifacts: true
          artifacts: "lunii-admin_darwin_amd64.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          tag: next
